### ISSUE TITLE
USB driver

### ISSUE THREAD

**Issue by kika123** [ms-iot/bsp#23]
Can the DWC driver source be added? Can this be made into the bsp.config.xml form?

**Comment by douglascgh** [comment]
The Raspberry Pi does not use the standard EHCI driver instead it uses an IP block from Synopsis (https://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf). So supporting USB required a customize driver that would not be publish publicly. Apologize for any inconvenience.

**Comment by kika123** [comment]
So the driver wasn't written by Microsoft but by Synopsys?

**Comment by douglascgh** [comment]
The source for the USB driver contains 3rd party component that cannot be released.

**Comment by IoTGirl** [comment]
Answer has been given - closing issue
