### ISSUE TITLE
Dma interrupt

### ISSUE THREAD

**Issue by esahannila** [ms-iot/bsp#32]
Is there any plans to implement dma interrupt option for spi like in PWM driver. 

Would be nice to able to use dma interruption to generate sine wave signals thru spi with MCP4921 DAC.

**Comment by IoTGirl** [comment]
Hi Lou,
Can you please review this request?
Sincere thanks,
IoTGirl

**Comment by saraclay** [comment]
Closing for now - please open an issue in our documentation repo if this still needs to be addressed: https://github.com/MicrosoftDocs/windows-iotcore-docs
