### ISSUE TITLE
[Windows 10 IoT Core] Raspberry PI 3 Model B - OS Shutdown does not put device into right state

### ISSUE THREAD

**Issue by alexiordan** [ms-iot/bsp#36]
I want to be able to turn on and off the Raspberry PI Model B running Windows 10 IoT Core version 10.0.16299.19 from the same button. After performing some research I end up connecting the button to GPIO3 and GND, in order to be able to start it up after shutting it down through software.
It didn't work.
Investigating this issue it turned out that the Shutdown command seems to not put the device into the right state. After shutting it down I receive 7 ACT Led blinks again and again instead of 10 ACT Led blinks once.

1. Is there any progress on rightly shutting down the Raspberry PI?
2. If point above is not an option, how else can I resolve my issue?

For reference I'll put here two other threads I collect my information from citing the most relevant post in each

- [MSDN - Windows IoT Forum: Raspberry PI - Wake Up from shutdown state](https://social.msdn.microsoft.com/Forums/en-US/deec2cc3-e36d-40b0-9105-cc6737402666/raspberry-pi-wake-up-from-shutdown-state?forum=WindowsIoT)

> Our Windows IoT development team built a Windows BSP for Raspberry Pi pretty much from scratch a couple of years ago. It was the first device we supported with Windows IoT Core. We took some shortcuts, particularly in areas where we couldn't find documentation or something just didn't work. **We do not completely shutdown the Raspberry Pi device as each of you reported. We had trouble accessing the power rail firmware and settled on putting the device in a sleep state.** 

- [Github RaspberryPI Firmware: [Windows 10 IoT Core] Wake Up Raspberry PI by GPIO means](https://github.com/raspberrypi/firmware/issues/900)

> On raspbian sudo halt results in 63 being written to the reset controller register and a watchdog reset being triggered. When bootcode.bin launches it checks for 63 in reset controller and enters a low powered halt state (before LAN, PLLs, clocks and power domains are enabled on the chip).
It will flash the ACT LED ten times at this point, it will go to sleep and only a GPIO event will allow it to continue (or a chip reset through RUN pin).
If you are not seeing ten flashes on the ACT LED then we aren't entering this low powered halt state.
Perhaps you should compare behaviour (and if it wakes up correctly) with raspbian.
If Windows 10 IoT does not enter the low powered halt state then you will need to ask the question there - modifying the firmware won't help.

Initially I thought there is one bootcode.bin per distro, in order to better listen to GPIO3 short to GND in boot process, but guys on raspberrypi firmware said: 

> There is only one sequence of firmware releases (containing one bootcode.bin and the four start.elf variants), so Windows 10 IoT has to use them.

**Comment by saraclay** [comment]
This may have been resolved due to recent updates. If this is not the case, please file an issue in our documentation repo: https://github.com/MicrosoftDocs/windows-iotcore-docs
