### ISSUE TITLE
Build error for 10.0.16299.0 ApiValidator.exe exited with code -1

### ISSUE THREAD

**Issue by VitorX** [ms-iot/bsp#38]
**Below is the orignal error:**
Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB3721	The command ""C:\Program Files (x86)\Windows Kits\10\bin\10.0.16299.0\x64\ApiValidator.exe" -DriverPackagePath:C:\ -SupportedApiXmlFiles:"C:\\UniversalDDIs.xml" -ModuleWhiteListXmlFiles:"C:\ModuleWhiteList.xml" -ApiExtractorExePath:"C:\\10.0.16299.0\x64"" exited with code -1.	bcmgpio	C:\Program Files (x86)\Windows Kits\10\build\WindowsDriver.common.targets	1746	

**And the details message for this issue is like below when execute the ApiValidator.exe manually:**

ApiValidation: Warning: API SdPortCompleteRequest in sdport.sys is not a supported universal API. rpisdhc.sys calls this API.
ApiValidation: Warning: API SdPortInitialize in sdport.sys is not a supported universal API. rpisdhc.sys calls this API.
ApiValidation: Warning: API SdPortWait in sdport.sys is not a supported universal API. rpisdhc.sys calls this API.
ApiValidation: Warning: API SdPortCompleteRequest in sdport.sys is not a supported universal API. bcm2836sdhc.sys calls this API.
ApiValidation: Warning: API SdPortInitialize in sdport.sys is not a supported universal API. bcm2836sdhc.sys calls this API.
ApiValidation: Warning: API SdPortReadRegisterUlong in sdport.sys is not a supported universal API. bcm2836sdhc.sys calls this API.
ApiValidation: Warning: API SdPortWait in sdport.sys is not a supported universal API. bcm2836sdhc.sys calls this API.
ApiValidation: Warning: API SdPortWriteRegisterUlong in sdport.sys is not a supported universal API. bcm2836sdhc.sys calls this API.

**Is there valid API for this these API doesn't support for universal API?**

**Comment by Amber-Kuo** [comment]
I met the same problem, anyone could help?
I also use VS 2017.

**Comment by Amber-Kuo** [comment]
Hi,
You can try to disable run ApiValidator for each project.

**Comment by VitorX** [comment]
@Amber-Kuo , thanks for the suggestion. I know disable the ApiValidator could fix this issue. But the bsp build with disable validation should NOT work for the 16299.

**Comment by thchi12** [comment]
The same problem with 17134 and vs2017

**Comment by saraclay** [comment]
Have you tried our recent build(s)? Closing this for now in case recent updates have fixed this. If you find this has not been fixed, please file an issue here: https://github.com/MicrosoftDocs/windows-iotcore-docs
