### ISSUE TITLE
Error: No package definition files found.

### ISSUE THREAD

**Issue by CharlieTao** [ms-iot/bsp#39]
Download and Unzip binaries,Run build.cmd,Can't build package.
Prompt "Error: No package definition files found."

**Comment by CharlieTao** [comment]
Run buildpkg .pkg.xml will generate wm.xml,but when Processing wm.xml,There's another error. (PkgGenCommon) : error : Failed DoConvert

**Comment by CharlieTao** [comment]
Modify .inf file can buile suceess.

[Manufacturer]                                                     [Manufacturer]
%MSFT%=Standard,ntarm     ------------>         %MSFT%=Standard,ntx86
[Standard.ntarm]                                                  [Standard.ntx86]

**Comment by saraclay** [comment]
Hi @CharlieTao, this may have been fixed in recent updates so I will close this for now. If that is not the case, please file an issue here: https://github.com/MicrosoftDocs/windows-iotcore-docs
