### ISSUE TITLE
Update to match recent official and Insider builds, add Model B+ drivers

### ISSUE THREAD

**Issue by Googulator** [ms-iot/bsp#41]
Recent official release and Insider builds for the Raspberry Pi appear to come with never drivers than what's available here, including some completely new drivers (e.g. USB).

In addition, an Insider build is now available for the Raspberry Pi 3 Model B+, bringing additional drivers for B+-specific devices.

Please update this repository with the new content found in recent builds.

**Comment by saraclay** [comment]
Hello, new content is being updated here: https://github.com/MicrosoftDocs/windows-iotcore-docs

**Comment by Googulator** [comment]
That repository contains documentation only. What's missing is the updated drivers provided in newer IoT Core builds themselves.
