### ISSUE TITLE
Windows 10 IoT on Raspberry PI 3 boot issue

### ISSUE THREAD

**Issue by alexiordan** [ms-iot/bsp#43]
Tested with a Raspberry PI 3 Model B
OS: 17134

1. I unplug RaspberryPI while Windows is still loading (point circle rotating). sometimes it happens when unplugging when in home screen, after Windows is loaded.
2. **I plug it back in, Windows does not start.** Only Power RED LED is on for about 60 seconds After those 60 seconds Act GREEN  LED starts a cycle of 7 times blink forever,
3. I unplug it
4. I plug it back in and Windows starts.

**Comment by saraclay** [comment]
Hi @alexiordan, this seems like a bug that needs to be reported. We ask that you file this as a bug in the Feedback Hub: https://social.msdn.microsoft.com/Forums/en-US/fad1c6a0-e578-44a7-8e8d-95cc28c06ccd/need-logs-if-your-device-hasnt-updated-to-the-latest-iotcore-version?forum=WindowsIoT
