### ISSUE TITLE
BSP for Intel Pentium N4200

### ISSUE THREAD

**Issue by JeffMushmo** [ms-iot/bsp#45]
We have a board that runs the Intel Pentium N42000 Quad Core 1.0 GHz - 2.50 GHz.

The Microsoft IoT documentation for BSPs only recommends a BSP that is for N3000 series Atom/Celeron/Pentium. 
https://docs.microsoft.com/en-us/windows-hardware/manufacture/iot/bsphardware#bsp-links

The motherboard we're using is also compatible with Intel Celeron N3350 Dual Core. And I'm wondering if this is in fact the same BSP for both? Or should I be looking for a different BSP for the N4200?

**Comment by parameshbabu** [comment]
This repo is for RPi bsp. Recommend to post such queries in https://social.msdn.microsoft.com/forums/en-US/home?forum=WindowsIoT for better traction.
